CHAIN_THAW_STEPS = [
    (
        {'base.base.fc.bias', 'base.base.fc.weight'},
        {'lr': 0.001}
    ),
    (
        {'base.base.layer4.2.bn3.bias', 'base.base.layer4.2.bn3.weight',
         'base.base.layer4.2.conv3.weight', 'base.base.layer4.2.bn2.bias',
         'base.base.layer4.2.bn2.weight', 'base.base.layer4.2.conv2.weight',
         'base.base.layer4.2.bn1.bias', 'base.base.layer4.2.bn1.weight',
         'base.base.layer4.2.conv1.weight', 'base.base.layer4.1.bn3.bias',
         'base.base.layer4.1.bn3.weight', 'base.base.layer4.1.conv3.weight',
         'base.base.layer4.1.bn2.bias', 'base.base.layer4.1.bn2.weight',
         'base.base.layer4.1.conv2.weight', 'base.base.layer4.1.bn1.bias',
         'base.base.layer4.1.bn1.weight', 'base.base.layer4.1.conv1.weight',
         'base.base.layer4.0.downsample.1.bias', 'base.base.layer4.0.downsample.1.weight',
         'base.base.layer4.0.downsample.0.weight', 'base.base.layer4.0.bn3.bias',
         'base.base.layer4.0.bn3.weight', 'base.base.layer4.0.conv3.weight',
         'base.base.layer4.0.bn2.bias', 'base.base.layer4.0.bn2.weight',
         'base.base.layer4.0.conv2.weight', 'base.base.layer4.0.bn1.bias',
         'base.base.layer4.0.bn1.weight', 'base.base.layer4.0.conv1.weight'},
        {'lr': 0.0001}
    ),
    (
        {'base.base.layer3.5.bn3.bias', 'base.base.layer3.5.bn3.weight',
         'base.base.layer3.5.conv3.weight', 'base.base.layer3.5.bn2.bias',
         'base.base.layer3.5.bn2.weight', 'base.base.layer3.5.conv2.weight',
         'base.base.layer3.5.bn1.bias', 'base.base.layer3.5.bn1.weight',
         'base.base.layer3.5.conv1.weight', 'base.base.layer3.4.bn3.bias',
         'base.base.layer3.4.bn3.weight', 'base.base.layer3.4.conv3.weight',
         'base.base.layer3.4.bn2.bias', 'base.base.layer3.4.bn2.weight',
         'base.base.layer3.4.conv2.weight', 'base.base.layer3.4.bn1.bias',
         'base.base.layer3.4.bn1.weight', 'base.base.layer3.4.conv1.weight',
         'base.base.layer3.3.bn3.bias', 'base.base.layer3.3.bn3.weight',
         'base.base.layer3.3.conv3.weight', 'base.base.layer3.3.bn2.bias',
         'base.base.layer3.3.bn2.weight', 'base.base.layer3.3.conv2.weight',
         'base.base.layer3.3.bn1.bias', 'base.base.layer3.3.bn1.weight',
         'base.base.layer3.3.conv1.weight', 'base.base.layer3.2.bn3.bias',
         'base.base.layer3.2.bn3.weight', 'base.base.layer3.2.conv3.weight',
         'base.base.layer3.2.bn2.bias', 'base.base.layer3.2.bn2.weight',
         'base.base.layer3.2.conv2.weight', 'base.base.layer3.2.bn1.bias',
         'base.base.layer3.2.bn1.weight', 'base.base.layer3.2.conv1.weight',
         'base.base.layer3.1.bn3.bias', 'base.base.layer3.1.bn3.weight',
         'base.base.layer3.1.conv3.weight', 'base.base.layer3.1.bn2.bias',
         'base.base.layer3.1.bn2.weight', 'base.base.layer3.1.conv2.weight',
         'base.base.layer3.1.bn1.bias', 'base.base.layer3.1.bn1.weight',
         'base.base.layer3.1.conv1.weight', 'base.base.layer3.0.downsample.1.bias',
         'base.base.layer3.0.downsample.1.weight', 'base.base.layer3.0.downsample.0.weight',
         'base.base.layer3.0.bn3.bias', 'base.base.layer3.0.bn3.weight',
         'base.base.layer3.0.conv3.weight', 'base.base.layer3.0.bn2.bias',
         'base.base.layer3.0.bn2.weight', 'base.base.layer3.0.conv2.weight',
         'base.base.layer3.0.bn1.bias', 'base.base.layer3.0.bn1.weight',
         'base.base.layer3.0.conv1.weight'},
        {'lr': 0.0001}
    ),
    (
        {'base.base.layer2.3.bn3.bias', 'base.base.layer2.3.bn3.weight',
         'base.base.layer2.3.conv3.weight', 'base.base.layer2.3.bn2.bias',
         'base.base.layer2.3.bn2.weight', 'base.base.layer2.3.conv2.weight',
         'base.base.layer2.3.bn1.bias', 'base.base.layer2.3.bn1.weight',
         'base.base.layer2.3.conv1.weight', 'base.base.layer2.2.bn3.bias',
         'base.base.layer2.2.bn3.weight', 'base.base.layer2.2.conv3.weight',
         'base.base.layer2.2.bn2.bias', 'base.base.layer2.2.bn2.weight',
         'base.base.layer2.2.conv2.weight', 'base.base.layer2.2.bn1.bias',
         'base.base.layer2.2.bn1.weight', 'base.base.layer2.2.conv1.weight',
         'base.base.layer2.1.bn3.bias', 'base.base.layer2.1.bn3.weight',
         'base.base.layer2.1.conv3.weight', 'base.base.layer2.1.bn2.bias',
         'base.base.layer2.1.bn2.weight', 'base.base.layer2.1.conv2.weight',
         'base.base.layer2.1.bn1.bias', 'base.base.layer2.1.bn1.weight',
         'base.base.layer2.1.conv1.weight', 'base.base.layer2.0.downsample.1.bias',
         'base.base.layer2.0.downsample.1.weight', 'base.base.layer2.0.downsample.0.weight',
         'base.base.layer2.0.bn3.bias', 'base.base.layer2.0.bn3.weight',
         'base.base.layer2.0.conv3.weight', 'base.base.layer2.0.bn2.bias',
         'base.base.layer2.0.bn2.weight', 'base.base.layer2.0.conv2.weight',
         'base.base.layer2.0.bn1.bias', 'base.base.layer2.0.bn1.weight',
         'base.base.layer2.0.conv1.weight'},
        {'lr': 0.0001}
    ),
    (
        {'base.base.layer1.2.bn3.bias', 'base.base.layer1.2.bn3.weight',
         'base.base.layer1.2.conv3.weight', 'base.base.layer1.2.bn2.bias',
         'base.base.layer1.2.bn2.weight', 'base.base.layer1.2.conv2.weight',
         'base.base.layer1.2.bn1.bias', 'base.base.layer1.2.bn1.weight',
         'base.base.layer1.2.conv1.weight', 'base.base.layer1.1.bn3.bias',
         'base.base.layer1.1.bn3.weight', 'base.base.layer1.1.conv3.weight',
         'base.base.layer1.1.bn2.bias', 'base.base.layer1.1.bn2.weight',
         'base.base.layer1.1.conv2.weight', 'base.base.layer1.1.bn1.bias',
         'base.base.layer1.1.bn1.weight', 'base.base.layer1.1.conv1.weight',
         'base.base.layer1.0.downsample.1.bias', 'base.base.layer1.0.downsample.1.weight',
         'base.base.layer1.0.downsample.0.weight', 'base.base.layer1.0.bn3.bias',
         'base.base.layer1.0.bn3.weight', 'base.base.layer1.0.conv3.weight',
         'base.base.layer1.0.bn2.bias', 'base.base.layer1.0.bn2.weight',
         'base.base.layer1.0.conv2.weight', 'base.base.layer1.0.bn1.bias',
         'base.base.layer1.0.bn1.weight', 'base.base.layer1.0.conv1.weight'},
        {'lr': 0.0001}),
    (
        {'base.base.bn1.bias', 'base.base.bn1.weight', 'base.base.conv1.weight'},
        {'lr': 0.0001}
    )
]